name: cicd
on: 
  workflow_dispatch:

jobs: 
   code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        run: echo "Code from github"  
    
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build docker container
        run: echo "Docker containe build"  
    
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Test the container
        run: echo "Test the container"  
  
  deployment: 
    runs-on: ubuntu-22.04
    steps:
      - name: Deploying the app
        run: echo "Deploying the app"  
