name: cicd
on: 
  workflow_dispatch:
   inputs:
      environment:
       description: This is the enveirmant where this workflow runs
       default: dev
       required: true
       type: choice
       options:
         - dev
         - prod
         - staging

jobs: 
   code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        run: echo "Code from github" 
        
   build:
    needs: code
    runs-on: ubuntu-22.04
    steps:
      - name: Build docker container
        run: echo "Docker containe build"
        
   test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Test the container
        run: echo "Test the container"
  
   deployment:
    needs: [build,test]
    runs-on: ubuntu-22.04
    steps:
      - name: Deploying the app
        run: echo "Deploying the app" 
