---
name: Hello Workflow testing
on: 
 push:
   branches: [main]
   paths:
     - '**.html'
jobs:
  greet:
    runs-on: ubuntu-22.04
    steps:
      - name: say Hello to users
        run: echo "hello Friends"
      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show all version of python and docker
        run: docker --version && python --version


 
    
  

   
